name: www

on:
  workflow_dispatch:
  
  schedule:
    - cron:  '00 15 * * *'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: "Confirmation of environment"
        run: | 
          echo "$SHELL"

      - name: "Run aã€€generate www"
        run: |
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git config --global user.name ${{ secrets.USER_NAME }}
          echo "w" >> README.md
          git add README.md
          git commit -m '[add] www'
          git push origin main
